# Name - Swatej Sonawane
# Github Username - swatejsonawane18
# USC ID - 9314761761

In [1]:
import pandas as pd
import numpy as np
import math
import os
import bootstrapped.bootstrap as bs
import bootstrapped.stats_functions as bs_stats

# References:

1. https://stackoverflow.com/questions/29206384/python-folder-names-in-the-directory
2. https://softhints.com/how-to-merge-multiple-csv-files-with-python/#:~:text=Steps%20to%20merge%20multiple%20CSV%20%28identical%29%20files%20with,files%20in%20the%20list%20and%20export%20as%20CSV

In [2]:
path = '../data/AReM'
folder_list=[]
folder_list = os.listdir(path)

In [3]:
folder_list.pop(2)
folder_list.pop(4)

'sensorsPlacement.pdf'

In [4]:
print(folder_list)

['bending1', 'bending2', 'cycling', 'lying', 'sitting', 'standing', 'walking']

# Q1 b

In [5]:
df_test = []

In [6]:
df_time_features=pd.DataFrame(columns=['mean1','std1','min1','1st Quart(1)','Median(1)','3rd Quart(1)','max1','mean2','std2','min2','1st Quart(2)','Median(2)','3rd Quart(2)','max2','mean3','std3','min3','1st Quart(3)','Median(3)','3rd Quart(3)','max3','mean4','std4','min4','1st Quart(4)','Median(4)','3rd Quart(4)','max4','mean5','std5','min5','1st Quart(5)','Median(5)','3rd Quart(5)','max5','mean6','std6','min6','1st Quart(6)','Median6','3rd Quart(6)','max6'])

In [7]:
headers = ["# Columns: time",  "avg_rss12",  "var_rss12",  "avg_rss13",  "var_rss13",  "avg_rss23", "var_rss23"]
for i in range(0,2):
    for j in range(0,2):
        temp = pd.read_csv('../data/AReM/'+folder_list[i]+'/dataset'+str(j+1)+'.csv', header=None,sep=',', skiprows = [0, 1, 2, 3, 4])
        tf_analysis_df = pd.DataFrame(temp.describe())
        tf_analysis_df = tf_analysis_df.iloc[1:,1:]
        tf_analysis_df =tf_analysis_df.T
        tf_arr=tf_analysis_df.to_numpy().flatten()
        df_time_features.loc[len(df_time_features)]=tf_arr
        df_test.append(temp)

In [8]:
for i in range(2,len(folder_list)):
    path = '../data/AReM/'+folder_list[i]
    dataset_list = os.listdir(path)
    for j in range(0,3):
        temp = pd.read_csv('../data/AReM/'+folder_list[i]+'/dataset'+str(j+1)+'.csv', header=None,sep=',', skiprows = [0, 1, 2, 3, 4])
        tf_analysis_df = pd.DataFrame(temp.describe())
        tf_analysis_df = tf_analysis_df.iloc[1:,1:]
        tf_analysis_df =tf_analysis_df.T
        tf_arr=tf_analysis_df.to_numpy().flatten()
        df_time_features.loc[len(df_time_features)]=tf_arr
        df_test.append(temp)

In [9]:
merged_df_test = pd.concat(df_test, ignore_index=True)

In [10]:
merged_df_test

           0      1      2      3     4      5     6
0          0  39.25   0.43  22.75  0.43  33.75  1.30
1        250  39.25   0.43  23.00  0.00  33.00  0.00
2        500  39.25   0.43  23.25  0.43  33.00  0.00
3        750  39.50   0.50  23.00  0.71  33.00  0.00
4       1000  39.50   0.50  24.00  0.00  33.00  0.00
...      ...    ...    ...    ...   ...    ...   ...
9115  118750  36.00   2.45  17.00  5.10  20.50  0.87
9116  119000  34.33   1.89  15.00  2.45  17.00  2.12
9117  119250  33.00   7.35  14.60  3.14  13.00  5.70
9118  119500  31.67   1.25  11.00  6.16  19.25  2.17
9119  119750  30.75  10.21  11.75  1.09  18.50  3.20

[9120 rows x 7 columns]

In [11]:
df_train=[]

In [12]:
headers = ["# Columns: time",  "avg_rss12",  "var_rss12",  "avg_rss13",  "var_rss13",  "avg_rss23", "var_rss23"]
for i in range(0,2):
    path = '../data/AReM/'+folder_list[i]
    dataset_list = os.listdir(path)
    for j in range(2,len(dataset_list)):
        temp = pd.read_csv('../data/AReM/'+folder_list[i]+'/dataset'+str(j)+'.csv',engine='python' ,header=None,delimiter='[ ,]',skiprows = [0, 1, 2, 3, 4])
        temp.columns= headers
        tf_analysis_df = pd.DataFrame(temp.describe())
        tf_analysis_df = tf_analysis_df.iloc[1:,1:]
        tf_analysis_df =tf_analysis_df.T
        tf_arr=tf_analysis_df.to_numpy().flatten()
        df_time_features.loc[len(df_time_features)]=tf_arr
        df_train.append(temp)

In [13]:
for i in range(2,len(folder_list)):
    path = '../data/AReM/'+folder_list[i]
    dataset_list = os.listdir(path)
    for j in range(3,len(dataset_list)):
        temp = pd.read_csv('../data/AReM/'+folder_list[i]+'/dataset'+str(j)+'.csv', header=None,sep=',',usecols=[0,1,2,3,4,5,6], skiprows = [0, 1, 2, 3, 4])
        temp.columns=headers
        tf_analysis_df = pd.DataFrame(temp.describe())
        tf_analysis_df = tf_analysis_df.iloc[1:,1:]
        tf_analysis_df =tf_analysis_df.T
        tf_arr=tf_analysis_df.to_numpy().flatten()
        df_time_features.loc[len(df_time_features)]=tf_arr
        df_train.append(temp)

In [14]:
len(df_train)

69

In [15]:
merged_df_train = pd.concat(df_train, ignore_index=True)

In [16]:
merged_df_train

,# Columns: time,avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23
0,0,43.67,0.47,24.75,0.43,30.00,0.00
1,250,43.33,0.47,25.33,0.47,30.00,0.00
2,500,42.75,0.83,25.25,0.83,30.50,0.50
3,750,41.75,0.43,20.50,3.35,30.75,0.83
4,1000,42.50,0.50,20.75,4.55,31.75,0.43
...,...,...,...,...,...,...,...
33114,118750,39.33,0.47,10.00,2.16,7.00,4.85
33115,119000,39.25,2.49,12.50,1.66,10.75,4.49
33116,119250,40.00,8.22,15.75,2.05,14.00,4.42
33117,119500,29.50,6.50,18.00,1.87,17.00,3.67
33118,119750,28.00,5.10,16.50,1.50,16.50,3.35

# Q1 c i

The types of time-domain features that are usually used in time series classification are:
Mean, Standard Deviation, 1st Quartile, Median, 3rd Quartile, Max, Min

# Q1 c ii

In [17]:
df_time_features

,mean1,std1,min1,1st Quart(1),Median(1),3rd Quart(1),max1,mean2,std2,min2,...,Median(5),3rd Quart(5),max5,mean6,std6,min6,1st Quart(6),Median6,3rd Quart(6),max6
0,40.624792,1.476967,37.25,39.2500,40.50,42.0000,45.00,0.358604,0.322605,0.0,...,35.00,36.00,38.25,0.570583,0.582915,0.0,0.0000,0.430,1.3000,1.92
1,42.812812,1.435550,38.00,42.0000,42.50,43.6700,45.67,0.372438,0.289158,0.0,...,33.00,34.50,38.50,0.571083,0.601010,0.0,0.0000,0.430,1.3000,3.11
2,24.562958,3.737514,12.75,23.1875,24.25,26.5000,51.00,0.590833,0.837408,0.0,...,23.75,27.00,30.00,0.700188,0.693720,0.0,0.4300,0.500,0.8700,4.97
3,27.464604,3.583582,0.00,25.5000,28.00,30.0000,42.75,0.449708,0.767197,0.0,...,18.00,20.75,33.00,1.122125,1.012342,0.0,0.4700,0.830,1.3000,6.76
4,37.177042,3.581301,24.25,34.5000,36.25,40.2500,45.00,2.374208,1.601799,0.0,...,20.00,21.75,25.50,2.921729,1.852600,0.0,1.5000,2.500,3.9000,9.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,34.253521,4.940741,21.50,30.9375,35.00,37.7500,51.25,4.457896,2.387192,0.0,...,15.75,18.00,24.25,3.500750,1.692378,0.0,2.1800,3.285,4.5575,8.32
84,33.586875,4.650935,19.50,30.2500,34.25,37.0000,45.33,4.576562,2.461077,0.0,...,16.00,18.25,25.00,3.259729,1.640243,0.0,2.0500,3.110,4.3225,8.32
85,34.322750,4.752477,19.75,31.0000,35.25,38.0000,45.50,4.456333,2.599284,0.0,...,15.75,17.75,23.25,3.432562,1.732727,0.0,2.1575,3.200,4.5650,9.67
86,34.546229,4.842294,19.50,31.2500,35.25,37.8125,46.00,4.371958,2.360448,0.0,...,15.75,17.75,22.75,3.338125,1.656742,0.0,2.1600,3.080,4.3350,10.00
87,34.873229,4.531720,23.50,31.7500,35.25,38.2500,46.25,4.380583,2.435437,0.0,...,16.00,18.00,23.50,3.424646,1.690960,0.0,2.1700,3.270,4.5000,9.51

In [18]:
print(len(df_time_features.columns))

42

# Q1 c iii

In [19]:
df_time_features.iloc[:,0:].std()

mean1            5.358921
std1             1.809298
min1            10.440661
1st Quart(1)     6.202549
Median(1)        5.419492
3rd Quart(1)     5.057110
max1             4.072827
mean2            1.576615
std2             0.892710
min2             0.000000
1st Quart(2)     0.948669
Median(2)        1.418605
3rd Quart(2)     2.127311
max2             5.175768
mean3            4.138163
std3             0.932121
min3             2.976511
1st Quart(3)     4.341220
Median(3)        4.155981
3rd Quart(3)     4.294173
max3             5.043960
mean4            1.167232
std4             0.462298
min4             0.000000
1st Quart(4)     0.841544
Median(4)        1.146788
3rd Quart(4)     1.559032
max4             2.219438
mean5            5.923437
std5             0.939792
min5             6.556653
1st Quart(5)     6.344323
Median(5)        6.034638
3rd Quart(5)     5.762994
max5             5.860510
mean6            1.156947
std6             0.517783
min6             0.000000
1st Quart(6)     0.759029
Median6          1.090382
3rd Quart(6)     1.526051
max6             2.532355
dtype: float64

In [20]:
time_domain_features = pd.DataFrame(df_time_features.iloc[:,0:].std())

In [21]:
bs_time_domain_features_std=[]
bs_time_domain_features_lb=[]
bs_time_domain_features_ub=[]
for i in range(0,len(df_time_features.columns)):
    result=(bs.bootstrap(df_time_features.iloc[:,i].to_numpy(),stat_func=bs_stats.std))
    bs_time_domain_features_std.append(result.value)
    bs_time_domain_features_lb.append(result.lower_bound)
    bs_time_domain_features_ub.append(result.upper_bound)

time_domain_features.insert(1,'bootstrap_value',bs_time_domain_features_std)
time_domain_features.insert(2,'bootstrap_lower_bound',bs_time_domain_features_lb)
time_domain_features.insert(3,'bootstrap_upper_bound',bs_time_domain_features_ub)

In [22]:
df_time_features.describe()

,mean1,std1,min1,1st Quart(1),Median(1),3rd Quart(1),max1,mean2,std2,min2,...,Median(5),3rd Quart(5),max5,mean6,std6,min6,1st Quart(6),Median6,3rd Quart(6),max6
count,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.0,...,88.000000,88.000000,88.000000,88.000000,88.000000,88.0,88.000000,88.000000,88.000000,88.000000
mean,39.104142,2.956764,29.113409,37.222244,39.058864,41.387017,45.632273,1.451275,0.991214,0.0,...,16.489034,18.736534,24.257614,1.615517,1.046578,0.0,0.901222,1.438352,2.141534,6.485909
std,5.358921,1.809298,10.440661,6.202549,5.419492,5.057110,4.072827,1.576615,0.892710,0.0,...,6.034638,5.762994,5.860510,1.156947,0.517783,0.0,0.759029,1.090382,1.526051,2.532355
min,24.562958,0.032038,0.000000,23.187500,24.250000,26.500000,30.000000,0.007167,0.055106,0.0,...,2.250000,5.542500,12.000000,0.383292,0.388372,0.0,0.000000,0.430000,0.500000,1.790000
25%,34.920167,1.440578,21.500000,31.730000,35.500000,38.250000,44.670000,0.366630,0.312042,0.0,...,13.730000,17.110000,21.187500,0.715370,0.613475,0.0,0.430000,0.500000,1.000000,4.500000
50%,39.469990,3.312713,29.250000,39.250000,39.500000,40.375000,45.750000,0.486167,0.455526,0.0,...,16.250000,18.415000,23.625000,0.922365,0.835344,0.0,0.470000,0.830000,1.220000,6.360000
75%,43.013250,4.464278,37.000000,42.000000,43.312500,45.000000,47.750000,2.731505,1.942496,0.0,...,18.000000,20.750000,25.625000,3.005229,1.637948,0.0,1.670000,2.615000,4.060000,8.600000
max,48.004167,7.684146,48.000000,48.000000,48.000000,54.000000,56.250000,4.576562,2.625516,0.0,...,36.000000,36.500000,38.670000,3.530500,1.963685,0.0,2.240000,3.340000,4.617500,13.610000

In [23]:
time_domain_features

,0,bootstrap_value,bootstrap_lower_bound,bootstrap_upper_bound
mean1,5.358921,5.328386,4.660794,6.087007
std1,1.809298,1.798988,1.584815,2.035498
min1,10.440661,10.381170,8.801210,12.062381
1st Quart(1),6.202549,6.167207,5.546402,6.871544
Median(1),5.419492,5.388611,4.702625,6.169869
3rd Quart(1),5.057110,5.028294,4.195186,5.975429
max1,4.072827,4.049620,3.009382,5.207158
mean2,1.576615,1.567631,1.414400,1.781377
std2,0.892710,0.887624,0.821002,0.984459
min2,0.000000,0.000000,0.000000,0.000000
1st Quart(2),0.948669,0.943263,0.838645,1.081389
Median(2),1.418605,1.410522,1.254328,1.624685
3rd Quart(2),2.127311,2.115189,1.915234,2.398618
max2,5.175768,5.146276,4.759085,5.655263
mean3,4.138163,4.114584,3.536888,4.830853
std3,0.932121,0.926810,0.708890,1.144480
min3,2.976511,2.959551,2.775996,3.195206
1st Quart(3),4.341220,4.316484,3.732640,5.011104
Median(3),4.155981,4.132300,3.540684,4.848136
3rd Quart(3),4.294173,4.269705,3.644660,5.030551
max3,5.043960,5.015220,4.269770,5.872648
mean4,1.167232,1.160581,1.095276,1.270141
std4,0.462298,0.459663,0.426029,0.504733
min4,0.000000,0.000000,0.000000,0.000000
1st Quart(4),0.841544,0.836749,0.782537,0.920535
Median(4),1.146788,1.140253,1.076568,1.252262
3rd Quart(4),1.559032,1.550148,1.463427,1.698662
max4,2.219438,2.206791,1.993859,2.459537
mean5,5.923437,5.889685,4.622748,7.405243
std5,0.939792,0.934437,0.781531,1.111862
min5,6.556653,6.519293,4.869191,8.580972
1st Quart(5),6.344323,6.308173,4.974408,7.814245
Median(5),6.034638,6.000252,4.704868,7.535066
3rd Quart(5),5.762994,5.730157,4.541722,7.128063
max5,5.860510,5.827117,4.879591,6.970325
mean6,1.156947,1.150355,1.080352,1.264509
std6,0.517783,0.514833,0.482320,0.561474
min6,0.000000,0.000000,0.000000,0.000000
1st Quart(6),0.759029,0.754704,0.696770,0.839214
Median6,1.090382,1.084169,1.011331,1.197428
3rd Quart(6),1.526051,1.517356,1.430075,1.667105
max6,2.532355,2.517925,2.227035,2.832172

# Q1 c iv

The three most important time-domain features are mean, min and max as they give a more accurate value.

# Q2

ISLR 3.7.4

1. The training RSS will be less for Cubic regression as there are more parameters involved i.e., more degrees of freedom, which can try to overfit.

2. If the true relation between X and Y is linear then test RSS for the linear regression will be less, as the values predicted for any input will be close to the actual value.

3. The training RSS will be less for Cubic regression as there are more parameters involved i.e., more degrees of freedom, which can try to overfit.

4. If the true relation between X and Y is not linear then test RSS for the cubic regression will be less, as the values predicted for any input will be close to the actual value which will be having a non-linear relation with the parameters.